/
/bin
/bin/sh
/sbin
/sbin/reboot
/usr
/usr/bin
/usr/bin/ls
/usr/bin/cat
/usr/lib
/usr/lib/libSystem.dylib
/usr/lib/libobjc.A.dylib
/usr/lib/libc++.dylib
/System
/System/Library
/System/Library/CoreServices
/System/Library/CoreServices/SystemVersion.plist
/System/Library/LaunchDaemons
/System/Library/LaunchDaemons/com.apple.launchd.plist
/System/Library/PrivateFrameworks
/System/Library/PrivateFrameworks/MobileCoreServices.framework
/System/Applications
/System/Applications/Safari.app
/System/Applications/Mail.app
/private
/private/var
/private/var/mobile
/private/var/mobile/Library
/private/var/mobile/Library/Preferences
/private/var/mobile/Library/Preferences/com.apple.springboard.plist
/private/var/tmp
/private/var/log
/private/var/log/system.log
/private/etc
/private/etc/hosts
/private/etc/passwd
/private/etc/group
/Applications
/Applications/AppStore.app
/Applications/Notes.app
/Applications/Calendar.app
/Library
/Library/Preferences
/Library/Preferences/SystemConfiguration
/Library/Preferences/SystemConfiguration/preferences.plist
